# Generated by Django 2.2.2 on 2019-06-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('prefLabel', models.CharField(max_length=100)),
                ('definition', models.CharField(blank=True, default='', max_length=300)),
            ],
            options={
                'ordering': ('prefLabel',),
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('prefLabel', models.CharField(max_length=100)),
                ('definition', models.CharField(blank=True, default='', max_length=300)),
            ],
            options={
                'ordering': ('prefLabel',),
            },
        ),
        migrations.CreateModel(
            name='Vocab',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('prefLabel', models.CharField(max_length=100)),
                ('definition', models.CharField(blank=True, default='', max_length=300)),
                ('collections', models.ManyToManyField(to='vocab.Collection')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='members',
            field=models.ManyToManyField(to='vocab.Concept'),
        ),
    ]
