# Generated by Django 2.2.4 on 2019-09-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('vocab', '0002_auto_20190925_0908'), ('vocab', '0003_auto_20190925_1155')]

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='prefLabel',
            field=models.CharField(max_length=1500),
        ),
        migrations.AddField(
            model_name='concept',
            name='notation',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
